apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg-helm-repo
  namespace: cnpg-system
spec:
  interval: 10m # How often to check for updates
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudnative-pg
      version: "v0.26.0" # {"$imagepolicy": "flux-system:cnpg:tag"}
      sourceRef:
        kind: HelmRepository
        name: cnpg-helm-repo
  targetNamespace: cnpg-system
  values:
    fullNameOverride: "ulthuan-cnpg"