apiVersion: v1
kind: Namespace
metadata:
  name: actual
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: &app actual
  namespace: *app
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.0.1
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app actual
  namespace: *app
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  targetNamespace: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app:
        strategy: Recreate
        containers:
          *app:
            image:
              repository: docker.io/actualbudget/actual-server
              tag: 26.5.2
              pullPolicy: IfNotPresent
            env:
              ACTUAL_OPENID_SERVER_HOSTNAME: &hostname budget.maximstroud.de

    service:
      *app:
        controller: *app
        ports:
          http:
            port: 5006

    ingress:
      main:
        className: nginx
        hosts:
          - host: *hostname
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: 5006
        tls:
          - hosts:
              - *hostname
            secretName: maximstroud.de-cert

    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 8Gi
        globalMounts:
          - path: /data
