apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/nginx/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ngf
  namespace: nginx-gateway
spec:
  interval: 1h
  chart:
    spec:
      chart: nginx-gateway-fabric
      version: "2.4.2"
      sourceRef:
        kind: HelmRepository
        name: nginx-gateway-fabric
        namespace: flux-system
