apiVersion: v1
kind: Namespace
metadata:
  name: nginx-gateway
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-gateway
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  interval: 1h
  chart:
    spec:
      chart: nginx-gateway-fabric
      version: "2.4.2"
      sourceRef:
        kind: HelmRepository
        name: nginx-gateway
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace