---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lubelogger
  namespace: flux-system
spec:
  image: ghcr.io/hargata/lubelogger
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: lubelogger
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lubelogger
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
