apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: gateway-api
  namespace: gateway
spec:
  interval: 12h
  url: oci://ghcr.io/kubernetes-sigs/gateway-api/release
  ref:
    tag: v1.5.0