---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: vikunja-config
  namespace: vikunja
spec:
  encryptedData:
    config.yml: AgBUxoMZEuNTSQDKKFBAOVdOyLIY9/Xc7K/8fw80s4O7EPeeqSZahIvqwicfBtjyBI0UetRfaLbFgHCZ442nKaTcMMGoJFUaok7mQTfVWEWUpYAHHpNDjVBTid6lHSdc1vZAzn1pFnHhdnvxkHVcNUrUsdfTiTvlm+2PGppm+IF/bnjhdGVDE8RB+MyQuNLaDahUKpuVohScDDyx2ia0nBNyJ8asEuChHF7IYBN7rjd/WodtlLh5a1PPl8sZRsXiCS7XPyxFDVNWhQCEBHvCX2AewJYHvQOIhJrz0T2nbKzvi8xlDlXOOn/puByxomwkMwPseMNxQqlFTVMgsWI1Wq4T93EvDiYVNIIGptWyf80EocogpLXDX7zUIWuHCHJgrfZCuYrbVFuZUYcXwAegWDWQ0kC96mPfRvQx/muT1S8DodJH/P6VqAIpLQxxUR3c95l3z7c9IrWcBd/jyjhJIgNUPRxxP+DEKGbQGOmAwLzCYZ/Nl437/bBJocE2AsCJJFvfVJp4EPk5+g1yfULzl4ahPsEIgA3X6qWeV5ttxVB/HqklFmfB46rgs63EX6/TgGEYgxgWWNyT6wsS9ognI5dys6WDtt77AEl/iK8HKs85VTSMLwBSzqaotkiGzzxx7lXaVmtu7fb1wZv+EkZavQCTtjpsPKsd12B0i5akWrRanqs/K00mv8HH4eBRdWYFntBv70WgHcpPjO2GLB4A6EgCtS/qBeccOQrSD5qB6749VPa714bhdZq9fymwqtryQ1SY5+pY84IWdoB0MuKj8vaEfZA/mXRETZzmijggtGmBUggr5isD8EfqW2H2Z2RpUla/7zCOZQ6c4AAqatUxthRfpbK3Pbs49MbnO6wxMr+URSKCn3NGXiZsCDSLDP9UPuVebu4wLeccOOF1bqmWk3kSaWB/SPdOqr57XFIsOvi93dasYQ2iZn4UZCQ/1w3f90eYUtLAtdBvj0RSeb39JfUiiexG2km2MDwU9NY3xZlYLa8fVdLczKX7rw7/Z30DPkApxi45PgMqbQ8jkgD1ZAiJ/XCXkWc4kKd+vTqApwEMw9BeROv6u2snMBRlKPgc7qcdYFaV+cjMhyJxiWzgso/xd4xlETaDG+5Hs7ppXB92yf/LSviNxzBhHthg/bW13ONURZtZ75yDeeUFzZt/tkDO5q+NQ+c6n0xIF7JR7gpOt0E8bbk4FchJbHHzhkS5o24LBtG/aqauZizmIfX9KsL7SQoUwG5aTdQ6XyAOkzDhi5KZ1uPPOOMIkKwqFd+vxbJWSIlMqtcN1njywTvOltan+YAsKJHthr34fcfSxdTL9QyhAkCdPuBmJjpjP6yoMNKk1xtGEJSaBKu+ZPrZu4k3raEmnLdWRb50BxgJa2eO6aL/+TLbVR+QnZFaUpy6wDSrTQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: vikunja-config
      namespace: vikunja
    type: Opaque
