apiVersion: v1
kind: Namespace
metadata:
  name: travel
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: travel
  namespace: travel
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.1.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app "travel"
  namespace: "travel"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  targetNamespace: *app
  values:
    controllers:
      *app:
        containers:
          app:
            image:
              repository: ghcr.io/seanmorley15/adventurelog
              tag: &version v0.13.0
            env:
              SITE_URL: "https://travel.maximstroud.de"
              DISABLE_REGISTRATION: "True"
              DISABLE_REGISTRATION_MESSAGE: "Registration is disabled, log in with The Science Team"
              SOCIALACCOUNT_ALLOW_SIGNUP: "True"
              FORCE_SOCIALACCOUNT_LOGIN: "True"
              DEBUG: True
              DJANGO_ADMIN_USERNAME: admin
              PGHOST: "cluster-travel-rw.travel.svc.cluster.local"
              BODY_SIZE_LIMIT: "5073741824"
            envFrom:
              - secretRef:
                  name: travel-creds

    service:
      *app:
        controller: *app
        ports:
          http:
            port: 80

    ingress:
      main:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: &hostname travel.maximstroud.de
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: http
        tls:
          - hosts:
              - *hostname
            secretName: maximstroud.de-cert

    persistence:
      media:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        globalMounts:
          - path: /code/media
