---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: mealie
  namespace: flux-system
spec:
  image: ghcr.io/mealie-recipes/mealie
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: mealie
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mealie
  policy:
    semver:
      range: '>=3.0.0 <4.0.0'
