apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx-helm-repo
  namespace: ingress-nginx
spec:
  interval: 10m # How often to check for updates
  url: https://kubernetes.github.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.9.0" # {"$imagepolicy": "flux-system:ingress-nginx:tag"}
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
      # -- This configuration defines if Ingress Controller should allow users to set
      # their own *-snippet annotations, otherwise this is forbidden / dropped
      # when users add those annotations.
      # Global snippets in ConfigMap are still respected
      allowSnippetAnnotations: true
