---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  image: kubernetes.github.io/ingress-nginx
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ingress-nginx
  policy:
    semver:
      range: '>=4.0.0 <5.0.0'
