---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCDwyr3lcOVriRAr8fQS+NWIPqt2s94LyzFPNN9HnsVw/hJyuKm+Ki8KiAtEPVCnPmzt3/Wb+DH0yQF8J4mFEsO6XpJklPJGusHTW+LrbAirPkKc828bzTF+G3sihwZbQm+Q7iwVe/CiMCJq6LY9CwlYtVyKzFQsjF1+chmOoErP9Po4QgjaJJtmRb81b+1mQrWyHwNCeTmXfdCBdRisSGU7pvMkCnXgeMisJFORw+ADa+elKb3kXa7OOZTTXoKk4BKr+QlW01rRu5bcVT+IcGxCBYcvEd50j+xrbgD++Qb3PkqMfezjY7VCO5D5MaHdKLOy4U36gDftyp6qBzq1B8COLOcdpkty1ffzHoUXVJtPcTgh+Mfh8HJOFX7HNIEmjZuXQy+q/yETypTIkn2ysorOmA86HYX2e9+YlGsvWdDl+wzSyj0jctfhceIjekI9Bs1ypIUOBlH0ev9XdLROrl+5/IyDzY5ieXydN+2HuL4coFK6nDTU7ta65NT37yf1gcQJwW3hf5yXlr3hr26whDBj/cHymiD1b8wHurnkhtWoFsC9GCjsDfdHsJMoeVt5ZmhkO32JaC7/WaT2PFskX3kk6Xi7ZfwFV64fLsfFKYx6W1m3bpydWJppwnC2zHFaaeOwmCgLkrp8a0xzLmpfwfP47Uwj2JajTAGzxGgYS14CD0ZPFx97jw9QlGhFySesn2XOB7ZqfREpzfA0+PG4R1gBdEA1xtceiVZRK6GOFASvEPT6ZCFwaF/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
