---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: actual-oidc-secret
  namespace: actual
spec:
  encryptedData:
    ACTUAL_OPENID_CLIENT_ID: AgAOC8A6a2bsAuOu2Nf3fhL+mYfaT5CuUTd/rIXY9ofcN7DF4GPG0Xl4HX0hq8TZRUqtJZ5Q7zGpszBKQcqiwcj8LBkoKjdsxPINyoD5xFJ19vFDAnGMhrm62HYKx2tEfmiZRG4QWzQvskSw7A4boh8hcepNpgoIRjZskJT7blnRl7GahwuGW8KcNFMG4BWqnkrYwmq48Awc0OSdUg2aely00lanOLZrZEC/ienG3KRZWBqRqSxTd3m18TztK0nIsI4JQBQormCz0vhvo3MRMl6oN5RBZ1njr1MI8s/Vjkn7W3wJxe5PO1NW9YdCg4hihd7CVUPSR7TdpQpxLuRIzwxxCacU9fCl8qyGcse3dlIENlP2tOw2XJODnsA44Kk26+mSAORCuguLy5gN5xkMcBsmtHmJphcQVVpDZxGCfDVTuyVJpayyxaPKmmKOFkDS3Dl1rjf8Rt3UKuEgGIPlZzxY/hUxhRO1EycCDH49p5mTbf0QfnyWPKJVvwdFsFaeg7KZJxFK/jjLUU8FOPWl/e2g+IwaPc578LLf6y3k/pKdtttuY08Q52rbIFFQ7Z5dDLB+4xswceUANOZbcmUSj/O33eWpu7/H8s4rT86xmotTR2z29jx8yS3b2ClpNY3PARLqRwZ2tFS/JZUGUf3N9Lxj5tBDE0FKowM5fl3OQWgLsti6UfmZTc38tK6V7/6rS5yDCY2yh30rnCL3x+QpyxAtLMx8h6xgDas6iz6VGZFyiRF//ezgIpOy
    ACTUAL_OPENID_CLIENT_SECRET: AgBuaRo4o7q0wyKlZewhicTZ49xVtbVLxvtdPLK70YlmabTihd+IpTCg5R/N/qouchusfjE8rh9drmGgkrSjcpB53O0nIejo9D3cb+4Xg32l7L1f9hzuLIqd9Ovj3BU4WcKNB8uHqMbvRHLe2IfRKgBmstWOv0VyomlINueRI53SNRNw2imPHma3gV2NxrxaCKfFztgbnpsXCMKQgdxJm8jC74ap5GeQSnC7Zyyf0Dk+hxv3bC0VoTyhlqbLTRLo/FpfV/fCn87ib5yeUWsaVFrw0zqZaSp5uTC3t4MZkcjM2wTb1wv+eC7lztBJLrgvFezKAIJzR50CRH+xK3R+HOSOhEQgiwX1G1uQwpCtQtF7zSJVSnSJCAmws7ZqhEZW4pVmRkxTvggaIbUM4NX8aw7IpbrZm0E87Uqa29lVQEvMwGuhxhIStHTj+GRSS+45Wz8Eap+75oIf/l+F4dqb2Hyeu5gQ/KHPOsgd4x1oQ4Ozsj6n8rJ/eg19RHOy+qwXa0xhTA+S6KaMQTBjoSbLl84IUAvcfhlgWXSEOq0XV41AkFBu3TKS4j9cdVZpmkbof6Vop+Gq0b7bnUabNT3brS16925cNeprIOlnJLwIhicV0R2ZyVBI/Mne7NexIEUBx9x6sj2oWNTZ8M0JsK/vb9Fp9hG+u/KjZG/p9xzg0q6baSA4/YsUVG0XZYkkiIOvox0f38CZNjbecXbWAIf7Uot78Dkol99LJCb34RpXWbxJdyP8BMShBL2rwKSrVFfy3qsONKhMEPfn5ql5CJY9jjJNTePnUrPheKledrG+lBLa1jKllY399IiU4r6yUnTh9+2y4Z41I7ohUHe7IEP6PoA1ZbPWXbfMfYZbuIW6FCzIaA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: actual-oidc-secret
      namespace: actual
