apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: irish-eyes
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            squat.ai/tun: "1"
        securityContext:
          privileged: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN