---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homeassistant-db-creds
spec:
  encryptedData:
    password: AgAFvoZF9HRdz6AzxUExVd6VwotZvy7D2G4O8XJEsSNNBZ1y4WxDGZjKW8lsyhJ+hdzgArKDjh3+5tvYV44WqrO/V9tSGQ26Tmn7oMy3IYNKZ3S68J5xZ/vOqVy0nDk18IQoFOdgFrtFpSZ/SCFHgA2yQwx8JS1oke5id1Iz1xpigY25PiIytN4iSa95+gAMb8B90TonOMuBX7erQ9W3X0FbFTP6yEacPvP4aVvDzOd2XwIQ/Is3uqkyTtDHXpJ9hVt4nIsIBkHFCraw6z0Qt3IU9HVCGKwFL4jPWXfGfXzKUuY31DrSHAzcppvn4lYd2RfYBGUyQ3uUCL5kf8sw/oRSyREhnYdItxrA6w+Buwdq7K5RHwQLM87u8hlvcJN2T2ZrSe7ejSVKgGOXZ2Dhm0ThQVbq/VnsLzy1xth5rWXKbqNBfqTXifWejNTllX8TsdpbKnEjL6tV5pUZJlxvzAj5JVnekfQj5DAsQlEb+mHt52ctqakLqiaDcsBkC0lQpKem/58EZrU0woaYbnHI8FVQyHkWsnbIxRIVyG6akfy70+KhfMQBMtPuWNeuE5VkHX1TAK9T8LGwXtEoZ0zL3DZhFtFAWIfxDme/Aa1IbmjET6ySeVN6GtZt5XgIXSFUobWebC1mTpatbzU3yxnqWU+LriIJWzfCk2FFB2HksuzDv6J4aDueKs4+gfNNNvp45/+H57KL7vLVdid6Dj0s7eEO6EPUbEnesMV8TEezk57OxR3WH9m7NBZNLN5/CA==
    username: AgAp9vn7tS+Iz42sfxH81IzkCbLde7Vn2mM/xphcFn1zca0uIDI8Ezru1HmqQjXY47NrVnU47f2om+BhGixH98l/e4lgosNulrMu2d81om2RyiGPQVxKbN2GObgv7AN2tLeSsFDvclnAGmIU6srCoYb0TYeDd6qATG+kNv8JLk9QB1a+USgy8k5VdXQFFeEwX0F/W8ajNdRzQbxqQFwqUuWg6cRDeEAeUZs9k2d+qgrTbwLS7MO3OaS9ti4kbZfw/TFBNrJGMGZ3ooGZouEHopnnXWn5495Bi1tbkGi2LT1kJuwiX87KpmuBkLToSC2vw9zdTpKOzczrn6jROlN4lYQ2MblaztnUPr5UDy4HBYguM32qotTavU7jyp3o7pjqSNKJgpGL9ivN/9XzFleSacErUEVhyLgfBftJ1uLKE0nrwbUWl0MtAkAiwuQSjKWD4KW3+8nlmxBm0JyT/yq+2V+dn1WNgRl4YZ59mdCylMukDgMQSvh0g2bqYiXp7WxfEf7WDsJGCNq/mhEplRow9Ixk6O/7xT0W9YYmWmBbQZ0DAnhahklww+BasEFpO9keANUz/ihDZiyxlodl0yz4N5dn7VK6h8/GN4hWuzu4f7b2NHyUOb3e08yVuyde/yC7NHET2ZVC2kFcu0husux+F9dXxX3qIT2G0SpZM5LQQGfA57WhYT3jXIPR1/R1BMzudIpGP/Qg3kqhLB+FNMI8TWjo
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homeassistant-db-creds
