---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
- service.yaml
- nfs-backup-target.yaml
- restic-backup-cronjob.yaml
- sealed-restic-backup-creds.yaml