apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./ulthuan/infra/sealedsecrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
