apiVersion: v1
kind: Namespace
metadata:
  name: garage
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 1h
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage
  ref:
    tag: v2.2.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 1h
  chart:
    spec:
      chart: script/helm/garage
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
  values:
    garage:
      replicationFactor: 1

    deployment:
      kind: DaemonSet

    persistence:
      meta:
        hostPath: /var/mnt/whatever/minio/meta
      data:
        hostPath: /var/mnt/whatever/minio/data

    nodeSelector:
      kubernetes.io/hostname: alithanar
