---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-project-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-project-insight-postgresql-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi