---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - immich-library-pvc.yaml
  - postgres-configmap.yaml
  - postgres-immich-clone.yaml
  - immich-sealed-secret.yaml