---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: zipline
  namespace: flux-system
spec:
  image: ghcr.io/diced/zipline
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: zipline
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zipline
  policy:
    semver:
      range: '>=4.0.0 <5.0.0'