apiVersion: v1
kind: Namespace
metadata:
  name: zipline
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zipline
  namespace: zipline
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.4.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zipline
  namespace: zipline
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: zipline
  targetNamespace: zipline
  values:
    global:
      alwaysAppendIdentifierToResourceName: true
    controllers:
      main:
        enabled: true
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/diced/zipline
              tag: 4.3.2
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: zipline-credentials

    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
            targetPort: 3000

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &hostname share.maximstroud.de
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: 3000
        tls:
          - hosts:
              - *hostname
            secretName: maximstroud.de-cert

    persistence:
      uploads:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Gi
      public:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
      themes:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
