apiVersion: v1
kind: Namespace
metadata:
  name: journal
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich-helm-repo
  namespace: journal
spec:
  type: "oci"
  interval: 10m # How often to check for updates
  url: oci://ghcr.io/immich-app/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: journal
spec:
  interval: 1m
  chart:
    spec:
      chart: immich
      version: "0.10.3"
      sourceRef:
        kind: HelmRepository
        name: immich-helm-repo
  targetNamespace: journal
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v2.0.0
            env:
              REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
              DB_HOSTNAME: "immich-labmouse"
              DB_USERNAME: "immich"
              DB_DATABASE_NAME: "immich"
              IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-insight-clearance
                    key: postgres-password
    immich:
      persistence:
        library:
          existingClaim: immich-library-project-insight
    valkey:
      enabled: true
    server:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                tag: v2.2.3
      ingress:
        main:
          enabled: true
          labels:
            tailscale.com/proxy-class: "irish-eyes"
          ingressClassName: tailscale
          annotations:
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: memories
              paths:
                - path: "/"
          defaultBackend:
            service:
              name: project-insight-server
              port:
                number: 2283
          tls:
            - hosts:
                - memories
    machine-learning:
      persistence:
        cache:
          type: persistentVolumeClaim