---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: immich-helm
  namespace: flux-system
spec:
  image: ghcr.io/immich-app/immich-charts/immich
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: immich-helm
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich-helm
  policy:
    semver:
      range: '>=0.0.0 <1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  image: ghcr.io/immich-app/immich-server
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: immich
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich
  policy:
    semver:
      range: '>=2.0.0 <3.0.0'
