apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-resources
  namespace: flux-system
spec:
  interval: 5m
  path: ./ulthuan/infra/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
