apiVersion: v1
kind: Namespace
metadata:
  name: syncthing
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: syncthing
  namespace: syncthing
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app syncthing
  namespace: *app
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  targetNamespace: *app
  values:
    controllers:
      syncthing:
        containers:
          app:
            image:
              repository: mirror.gcr.io/syncthing/syncthing
              tag: 2.0.13
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 15m
                memory: 150M
              limits:
                memory: 300M
      browser:
        containers:
          app:
            image:
              repository: mirror.gcr.io/filebrowser/filebrowser
              tag: v2.54.0
            env:
              TZ: America/Chicago
              FB_DATABASE: /config/filebrowser.db
              FB_ROOT: /var/syncthing
              FB_LOG: stdout
              FB_NOAUTH: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &browserPort 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 500Mi
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      app:
        controller: syncthing
        primary: true
        ports:
          http:
            port: 8384
            primary: true
      listen:
        controller: syncthing
        type: LoadBalancer
        ports:
          listen:
            port: 22000
            protocol: TCP
            targetPort: 22000
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027
      browser:
        controller: browser
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: sync
          tailscale.com/proxy-class: "irish-eyes"
        labels:
          tailscale.com/proxy-class: "irish-eyes"
        ports:
          http:
            port: 80
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        suffix: config
        advancedMounts:
          browser:
            app:
              - path: /config
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteMany
        size: 100Gi
        globalMounts:
          - path: /var/syncthing
