apiVersion: v1
kind: Service
metadata:
  name: garage
  labels:
    tailscale.com/proxy-class: "irish-eyes"
  annotations:
    tailscale.com/hostname: garage
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: garage
  ports:
  - name: s3port
    port: 80
    targetPort: 3900
