apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale-helm-repo
  namespace: tailscale
spec:
  interval: 10m # How often to check for updates
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/tailscale-operator
      version: "0.3.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale-helm-repo
  targetNamespace: tailscale
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
