apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/tailscale-operator
      version: "0.3.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
