apiVersion: v1
kind: Namespace
metadata:
  name: gathio
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gathio
  namespace: flux-system
spec:
  interval: 5m
  path: ./ulthuan/apps/gathio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
