---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: gathio
  namespace: flux-system
spec:
  image: ghcr.io/lowercasename/gathio
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: gathio
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gathio
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
