apiVersion: v1
kind: Namespace
metadata:
  name: vikunja
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vikunja-helm-repo
  namespace: vikunja
spec:
  type: "oci"
  interval: 10m # How often to check for updates
  url: oci://ghcr.io/go-vikunja/helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: vikunja
spec:
  interval: 1m
  chart:
    spec:
      chart: vikunja
      version: "1.1.0" # {"$imagepolicy": "flux-system:vikunja-helm:tag"}
      sourceRef:
        kind: HelmRepository
        name: vikunja-helm-repo
  targetNamespace: vikunja
  values:
    vikunja:
      persistence:
        config:
          type: secret
          name: vikunja-config
      image:
        repository: vikunja/vikunja
        tag: unstable # {"$imagepolicy": "flux-system:vikunja:tag"}
      ingress:
        main:
          enabled: true
          labels:
            tailscale.com/proxy-class: "irish-eyes"
          annotations:
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: tasks
              paths:
                - path: /
          defaultBackend:
            service:
              name: vikunja-vikunja
          ingressClassName: tailscale
          tls:
            - hosts:
                - tasks
      env:
        # To utilize a secret in the environment variables, you can do something like the following: https://github.com/bjw-s/helm-charts/blob/a081de53024d8328d1ae9ff7e4f6bc500b0f3a29/charts/library/common/values.yaml#L141-L145
        # You could also use MySQL or SQLite, but we recommend PostgreSQL.
        # https://vikunja.io/docs/config-options/#type
        VIKUNJA_SERVICE_PUBLICURL: "https://tasks.kingfisher-halfmoon.ts.net"
        VIKUNJA_DATABASE_TYPE: "postgres"
        VIKUNJA_DATABASE_USER:
          valueFrom:
            secretKeyRef:
              name: vikunja-credentials
              key: postgres-username
        VIKUNJA_DATABASE_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: vikunja-credentials
              key: postgres-password
        VIKUNJA_DATABASE_NAME:
          valueFrom:
            secretKeyRef:
              name: vikunja-credentials
              key: postgres-database
        VIKUNJA_DATABASE_DATABASE: vikunja
        VIKUNJA_DATABASE_HOST: vikunja-vikunja-postgresql
        VIKUNJA_DEFAULTSETTINGS_EMAIL_REMINDERS_ENABLED: true
        VIKUNJA_DEFAULTSETTINGS_WEEK_START: 1
        VIKUNJA_DEFAULTSETTINGS_OVERDUE_TASKS_REMINDERS_TIME: 7:00
        VIKUNJA_DEFAULTSETTINGS_DISCOVERABLE_BY_NAME: true
        VIKUNJA_MAILER_ENABLED: true
        VIKUNJA_MAILER_HOST:
          valueFrom:
            secretKeyRef:
              name: smtp-secrets
              key: smtp-host
        VIKUNJA_MAILER_USERNAME:
          valueFrom:
            secretKeyRef:
              name: smtp-secrets
              key: smtp-username
        VIKUNJA_MAILER_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: smtp-secrets
              key: smtp-password
        VIKUNJA_MAILER_FROMEMAIL: tasks@maximultimatum.de
    postgresql:
      auth:
        existingSecret: vikunja-credentials
    typesense:
      enabled: true
      env:
        TYPESENSE_DATA_DIR: /data
        TYPESENSE_API_KEY: typesense
      persistence:
        data:
          enabled: true
          accessMode: ReadWriteOnce
          size: 2Gi
      image:
        repository: docker.io/typesense/typesense
        tag: 0.25.1
        pullPolicy: IfNotPresent
