apiVersion: v1
kind: Namespace
metadata:
  name: frigate
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 10m # How often to check for updates
  url: "https://blakeblackshear.github.io/blakeshome-charts"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 1h
  chart:
    spec:
      chart: frigate
      version: 7.8.0
      sourceRef:
        kind: HelmRepository
        name: frigate
  targetNamespace: frigate
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: 0.16.2-tensorrt
    env:
      TZ: CST
    envFromSecrets:
      - frigate-rstp-credentials
    securityContext:
      privileged: true
    # -- frigate configuration - see [Docs](https://docs.frigate.video/configuration/index) for more info
    config: |
      mqtt:
        # Required: host name
        host: 192.168.42.1
        # Optional: port (default: shown below)
        port: 1883
        # Optional: topic prefix (default: shown below)
        # WARNING: must be unique if you are running multiple instances
        topic_prefix: frigate
        # Optional: client id (default: shown below)
        # WARNING: must be unique if you are running multiple instances
        client_id: frigate
        # Optional: user
        # user: mqtt_user
        # Optional: password
        # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
        #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
        # password: password
        # Optional: interval in seconds for publishing stats (default: shown below)
        stats_interval: 60
      detectors:
        onnx:
          type: onnx
      model:
        model_type: yolonas
        width: 320 # <--- should match whatever was set in notebook
        height: 320 # <--- should match whatever was set in notebook
        input_pixel_format: bgr
        input_tensor: nchw
        path: "plus://0a01efc8a5df1c019c5278953c8d9b39"
        labelmap_path: /labelmap/coco-80.txt

      objects:
        track:
          - person
          - face
          - dog
          - cat
          - bicycle
          - motorcycle
          - amazon
          - usps
          - ups
          - fedex
          - package
          
      record:
        enabled: True
        retain:
          days: 1
          mode: all
        alerts:
          retain:
            days: 15
            mode: motion
        detections:
          retain:
            days: 15
            mode: motion

      face_recognition:
        enabled: True

      snapshots:
        enabled: true
        retain:
          default: 15

      cameras:
        front_door: # camera name
          zones:
            front_yard:
              coordinates: 0,1,0,0.855,0.362,0.484,0.813,0.456,0.815,1
          review:
            detections:
              required_zones:
                - front_yard
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.4.84:554/cam/realmonitor?channel=1&subtype=0
                roles:
                  - detect
                  - record
          detect:
            enabled: true
            width: 1280
            height: 720
          # fps: 5
        back_door:
          zones:
            back_yard:
              coordinates: 1,1,0.998,0.371,0.456,0.303,0.445,0.373,0,0.689,0,1
          review:
            detections:
              required_zones:
                - back_yard
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RSTP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.4.85:554/cam/realmonitor?channel=1&subtype=0
                roles:
                  - detect
                  - record
          detect:
            enabled: true
            width: 1280
            height: 720
          # fps: 5

    service:
      type: LoadBalancer
      port: 5000
      annotations:
        tailscale.com/hostname: pierce
      labels:
        tailscale.com/proxy-class: "irish-eyes"
    persistence:
      config:
        enabled: true
        size: 10Gi
      media:
        enabled: true
        size: 300Gi
        skipuninstall: true
    nodeSelector:
      has: gpu
