apiVersion: v1
kind: Namespace
metadata:
  name: comfyui
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: comfyui
  namespace: comfyui
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.4.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app comfyui
  namespace: comfyui
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: comfyui
  targetNamespace: comfyui
  values:
    controllers:
      comfyui:
        type: statefulset
        pod:
          runtimeClassName: nvidia
          nodeSelector:
            has: gpu
        containers:
          app:
            image:
              repository: ghcr.io/ai-dock/comfyui
              tag: v2-cuda-12.1.1-base-22.04-v0.2.7@sha256:ca4c95d4d4743d7d5683e57f5e0358fe586bc57578f66c2a844e9fa0650cc619
            env:
              AUTO_UPDATE: "false"
              DIRECT_ADDRESS_GET_WAN: "true"
              SERVICEPORTAL_URL: "comfyui.${SECRET_DOMAIN}"
              WEB_ENABLE_AUTH: "false"
              WORKSPACE: "/workspace"
              CF_QUICK_TUNNELS: "false"
              SERVERLESS: "false"
              PROVISIONING_SCRIPT: "https://raw.githubusercontent.com/ai-dock/comfyui/main/config/provisioning/flux.sh"
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 500m
                memory: 16Gi
              limits:
                memory: 32Gi
    service:
      app:
        controller: comfyui
        ports:
          http:
            port: &httpPort 8188

    ingress:
      app:
        enabled: true
        className: tailscale
        annotations:
          tailscale.com/hostname: imagine
        labels:
          tailscale.com/proxy-class: "irish-eyes"
        hosts:
          - host: imagine
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
              - imagine

    persistence:
      workspace:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        globalMounts:
          - path: /workspace
      output:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        globalMounts:
          - path: /workspace/ComfyUI/output

      config:
        type: configMap
        accessMode: ReadWriteOnce
        name: comfyui-configmap
        size: 100Mi
        advancedMounts:
          comfyui:
            app:
              - path: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/config.ini
                subPath: config.ini
                readOnly: true
