apiVersion: v1
kind: Service
metadata:
  name: stirling
  labels:
    tailscale.com/proxy-class: "irish-eyes"
  annotations:
    tailscale.com/hostname: pdfs
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: stirling-pdf
  ports:
  - name: http
    port: 80
    targetPort: 8080
