apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    tailscale.com/proxy-class: "irish-eyes"
  annotations:
    tailscale.com/hostname: torrents
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: qbittorrent
  ports:
    - name: https
      port: 443
      targetPort: 8080
    - name: http
      port: 80
      targetPort: 8080
