---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  image: ghcr.io/tailscale/k8s-operator
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: tailscale
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: tailscale
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
