apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn-helm-repo
  namespace: longhorn-system
spec:
  interval: 10m # How often to check for updates
  url: https://charts.longhorn.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1m
  chart:
    spec:
      chart: longhorn
      version: "v1.8.2" # {"$imagepolicy": "flux-system:longhorn:tag"}
      sourceRef:
        kind: HelmRepository
        name: longhorn-helm-repo
  targetNamespace: longhorn-system
  values:
    persistence:
      defaultClass: true