---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgA7NfxsBiEzzPaLntik6X0h1UnBu5dh4iXtXELcnnYd5pg/qRRuTfB0ZuoEJ4GH1EqnQF9hFsehGtD/2os33NX50hzKaYPaJASDTEkpKUkdmzgWsV7k4Jgxsya7UhPor1RrHN5LcLcIErazy4TZDZ9og/HRPzhXyjOQkZbQbRDgU8gSJ5LqCWOL470ByAT2OB2qBqdv0YXxz6Bzvjk1m+PAP5bcWFXmSD6hwyWW+CtffYxc+h8wC0OmwU9MqYG4WeOL1ZzxzZGc+iR3FA4JP2yZH1LFmdDrFE5h65LSoDngFZRg8jHRk6vyeN9LUNs4c1wlzorIAFOz4wlbzj7lIGKRhoorQ1CPo1w5NrBypmzxTJuoyEZfdV6MExACjYiyfu7A06I20YV4CSE4jJnKmtTt5LVbYuHwe/+WCmBriafdCfXkALAjSSCtDH6R0lbqkmupemwRi9h3x51nDHySC7e4JrJBp16H0Jta6Rfn2m17fcuX1yLvpSW1WCna84qUSHHtl2LUQoHL9luvdvGZpxUOyj3BCt38Ahmiqba32TaZG84Gp0vVknn6dujLV8QURLqSvZ5k6s9EbOho4LN4MePBJs76qiiM7gtqhbMbFGnHP8Di1+rgp+IS5WQoKeaJtl+ThwGMAFkK599/nsxO8OblT5r4xRQtpz5mniuvyTxNsQE3aq7gbZcp6TlpUByJYQ8TvobYEfBd2MDKp0bYIUEAhQ==
    client_secret: AgAA+saas3ejQzhh+7W7MYfwqECJFneYYChDo7OX/ueFgGIbcJzfRj4GGsAH9+xSxJa8vq+1f6gnOg4V0S2HrD8Ww5o8ouYHpNJIzBD4wBv0M9YSDrd8AKV1jmbj2INbYyiZzm1tlNAs3EjcjO+8FYqCFjLbCzxIgbSAI/7lopoinX01wEp7gdu7/aPgS2einES/X11AyAeWo4spvGSF8aYN0tV6HXqF1drWb4QT/KTdXiF8olQCJZnbrF2Vnq3CXS3YxPQImKZV7dZuQwatUrM6DH0xy8YvXUC2zWuB8nAigtMq7yTfLNA5FLHLQ6qCfJMbqMseNrfvYx0NFJzkbor/KRhxhTKtp1/fWQ4asLpabYaKQgQKS7dUuFlhFr1tyQAFmk9g4AuOY/Q3Zm5GMSkYZqYhNwIyhFzKSga/yFW/+Z97JgJgdaSdAH7lBDbv/dqLZ2JFHExKGd29dfgPpbiNse1kUd04bq/lDhAifnoQgbDeqJGT1M93dNy1H11vxYnvtoZ4N1b5+/m7bjPSYKYiJUsuxVjLVuHHRd3b96y3V0BuOsrTJHAMWZYhMkfpk2n/ZQG9kdic3REKOmzeaNzdRizDZ8ROD2RXuO4Cye2qevCfTGFKUicWnhDGg2U7ECe0bDgbLWXroRWBAW3BnRZHTVhYmnaWA9Kou6FOHnfI6gB5CYXg0w6gWp8vrTwq7fygULdjkQ8zDPMuNwQJauSij8gzCI0rKNH0lBK4CqDDwd02gq8H7hU+baVYOJ6TpdNzVVFUcHnvl2MEAtMBJ6AO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
