apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: events.maximstroud.de-cert
spec:
  dnsNames:
    - "events.maximstroud.de"
  secretName: events.maximstroud.de-cert
  issuerRef:
    name: letsencrypt-cloudflare-issuer
    kind: ClusterIssuer
